-- Adiciona colunas de métricas brutas da planilha na tabela startups
ALTER TABLE public.startups
  ADD COLUMN IF NOT EXISTS aulas          INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS mentorias      INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS canvas_feito   BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS entrevistas    BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS mvp_funcional  BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS pessoas_testando  BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS clientes_pagantes BOOLEAN NOT NULL DEFAULT FALSE;
